version: "3.8"
services:
  books-nginx:
    image: nginx:stable-alpine
    container_name: books-nginx
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books-php
      - books-db
    networks:
      - books-network
  books-php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: books-php
    ports:
      - "9000:9000"
    volumes:
      - ./public_html:/var/www/html
    networks:
      - books-network
  books-db:
    image: mysql:8
    container_name: books-db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - books-network
  books-phpmyadmin:
    image: phpmyadmin
    container_name: books-phpmyadmin
    restart: always
    depends_on:
      - books-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: books-db
    networks:
      - books-network
networks:
  books-network:
    driver: bridge